USE [master]
GO
/****** Object:  Database [Books]    Script Date: 29/07/2022 09:56:52 ******/
CREATE DATABASE [Books]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'Books', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Books.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'Books_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Books_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Books] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Books].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Books] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Books] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Books] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Books] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Books] SET ARITHABORT OFF
GO
ALTER DATABASE [Books] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Books] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Books] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Books] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Books] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Books] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Books] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Books] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Books] SET  DISABLE_BROKER
GO
ALTER DATABASE [Books] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Books] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Books] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Books] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Books] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Books] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Books] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Books] SET RECOVERY SIMPLE
GO
ALTER DATABASE [Books] SET  MULTI_USER
GO
ALTER DATABASE [Books] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Books] SET DB_CHAINING OFF
GO
ALTER DATABASE [Books] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [Books] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [Books] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [Books] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO
ALTER DATABASE [Books] SET QUERY_STORE = OFF
GO
USE [Books]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[AuthorID] [int] NOT NULL,
	[FirstName] [varchar](25) NOT NULL,
	[MiddleName] [varchar](25) NULL,
	[LastName] [varchar](50) NOT NULL,
	[Gender] [varchar](2) NOT NULL,
	[DateOfBirth] [datetime] NOT NULL,
	[DateOfDeath] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AuthorBook]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AuthorBook](
	[AuthorID] [int] NOT NULL,
	[BookID] [int] NOT NULL,
 CONSTRAINT [PK_AuthorBookKey] PRIMARY KEY CLUSTERED
(
	[AuthorID] ASC,
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[BookID] [int] NOT NULL,
	[Title] [varchar](100) NOT NULL,
	[PublicationDate] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookFormat]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookFormat](
	[BookID] [int] NOT NULL,
	[FormatID] [int] NOT NULL,
	[Price] [float] NULL,
	[QuantityOnHand] [int] NULL,
 CONSTRAINT [PK_BookFormatKey] PRIMARY KEY CLUSTERED
(
	[BookID] ASC,
	[FormatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookGenre]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookGenre](
	[BookID] [int] NOT NULL,
	[GenreID] [int] NOT NULL,
 CONSTRAINT [PK_BookGenreKey] PRIMARY KEY CLUSTERED
(
	[BookID] ASC,
	[GenreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Format]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Format](
	[FormatID] [int] NOT NULL,
	[FormatName] [varchar](12) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[FormatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genre]    Script Date: 29/07/2022 09:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genre](
	[GenreID] [int] NOT NULL,
	[GenreName] [varchar](25) NOT NULL,
PRIMARY KEY CLUSTERED
(
	[GenreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AuthorBook]  WITH CHECK ADD  CONSTRAINT [FK_AuthorBook_Author] FOREIGN KEY([AuthorID])
REFERENCES [dbo].[Author] ([AuthorID])
GO
ALTER TABLE [dbo].[AuthorBook] CHECK CONSTRAINT [FK_AuthorBook_Author]
GO
ALTER TABLE [dbo].[AuthorBook]  WITH CHECK ADD  CONSTRAINT [FK_AuthorBook_Book] FOREIGN KEY([BookID])
REFERENCES [dbo].[Book] ([BookID])
GO
ALTER TABLE [dbo].[AuthorBook] CHECK CONSTRAINT [FK_AuthorBook_Book]
GO
ALTER TABLE [dbo].[BookFormat]  WITH CHECK ADD  CONSTRAINT [FK_BookFormat_Book] FOREIGN KEY([BookID])
REFERENCES [dbo].[Book] ([BookID])
GO
ALTER TABLE [dbo].[BookFormat] CHECK CONSTRAINT [FK_BookFormat_Book]
GO
ALTER TABLE [dbo].[BookFormat]  WITH CHECK ADD  CONSTRAINT [FK_BookFormat_Format] FOREIGN KEY([FormatID])
REFERENCES [dbo].[Format] ([FormatID])
GO
ALTER TABLE [dbo].[BookFormat] CHECK CONSTRAINT [FK_BookFormat_Format]
GO
ALTER TABLE [dbo].[BookGenre]  WITH CHECK ADD  CONSTRAINT [FK_BookGenre_Book] FOREIGN KEY([BookID])
REFERENCES [dbo].[Book] ([BookID])
GO
ALTER TABLE [dbo].[BookGenre] CHECK CONSTRAINT [FK_BookGenre_Book]
GO
ALTER TABLE [dbo].[BookGenre]  WITH CHECK ADD  CONSTRAINT [FK_BookGenre_Genre] FOREIGN KEY([GenreID])
REFERENCES [dbo].[Genre] ([GenreID])
GO
ALTER TABLE [dbo].[BookGenre] CHECK CONSTRAINT [FK_BookGenre_Genre]
GO
ALTER TABLE [dbo].[Author]  WITH CHECK ADD CHECK  (([Gender]='gq' OR [Gender]='p' OR [Gender]='a' OR [Gender]='nb' OR [Gender]='gn' OR [Gender]='tg' OR [Gender]='f' OR [Gender]='m'))
GO
USE [master]
GO
ALTER DATABASE [Books] SET  READ_WRITE
GO
